# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: indigo

# SEO
marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: "ProfessionalService"
    org_name: "Solcraft City Limited"
    description: "Consultancy focused on Solution crafting and software engineering"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Solcraft City"
      # Logo filename in `assets/media/` folder
      filename: ""
    button:
      enable: false
      text: ""
      url: ""
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: "© {year} Solcraft City Limited"

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
